### ISSUE TITLE
讨论： profiles继承

### ISSUE THREAD

**Issue by waterbang** [BioforestChain/pkgm#49]
讨论：现在的userConfig结构为：
```
{
name:'a-adw',
profiles:['web','node'],
build:[
  {
      name: 'a-web',
      profiles:[ 'prod']
  },
   {
      name: 'a-node',
      profiles: ['dev']
  },
]
}
```
现在希望这个存在父子关系，build里面的profiles会继承外部profiles，相当于现在在build里面是这样的：
```
 {
      name: 'a-web',
      profiles:[ 'prod'，'web','node']
  },
```
但是已经经过互斥处理，因此在web模块下并不会导出node相关的.
现在已经规定的互斥为 **web/node**,**dev/prod**

所以我这样给了build的profiles继承外部的profiles会不会出现一些与大伙代码冲突的情况🌞。

**Comment by ryanroe** [comment]
现阶段来说，影响不大，毕竟到了v3之后，profile的形态可能就不是现在这样了

**Comment by waterbang** [comment]
> 现阶段来说，影响不大，毕竟到了v3之后，profile的形态可能就不是现在这样了

收到，那俺关闭了
